### ISSUE TITLE
In React, can't set className for iconpark-icon,  only set the class attribute

### ISSUE THREAD

**Issue by Zero-Rock** [bytedance/IconPark#293]
when i use className for className, like this
![image](https://user-images.githubusercontent.com/23442144/126635486-cfa549a7-bf93-4378-a543-4379c0a890c5.png)

className will be parsed classname

![image](https://user-images.githubusercontent.com/23442144/126635219-c45ba7bb-f084-434f-bc60-f7cc949220c6.png)

**Comment by loveDstyle** [comment]
Yes, it's a confusing thing.😅  To use CSS class on a web component (a custom element to be specific) in React, you should use `class` instead of `className`. 

This is mentioned in React doc: https://reactjs.org/docs/web-components.html#using-web-components-in-react
![image](https://user-images.githubusercontent.com/18344013/126636968-10ac0d5e-8a0b-49b6-8492-cfd7797bb5c9.png)


There's also an [issue](url(https://github.com/facebook/react/issues/17944#issuecomment-581091775)  related to this topic.

**Comment by Zero-Rock** [comment]
I see， this is internal implementation of React. but this usage is still confusing, thank you anyway
